const personagens = [
{
nome:"Naruto Uzumaki",
vila:"Folha",
rank:"Hokage",
chakra:100,
nivel:99,
imagem:"assets/naruto.jpg"
},

{
nome:"Sasuke Uchiha",
vila:"Folha",
rank:"Ninja Renegado",
chakra:98,
nivel:98,
imagem:"assets/sasuke.jpg"
},

{
nome:"Sakura Haruno",
vila:"Folha",
rank:"Jounin",
chakra:90,
nivel:92,
imagem:"assets/sakura.jpg"
},

{
nome:"Kakashi Hatake",
vila:"Folha",
rank:"Hokage",
chakra:94,
nivel:96,
imagem:"assets/kakashi.jpg"
},

{
nome:"Gaara",
vila:"Areia",
rank:"Kazekage",
chakra:95,
nivel:95,
imagem:"assets/gaara.jpg"
},

{
nome:"Rock Lee",
vila:"Folha",
rank:"Jounin",
chakra:85,
nivel:89,
imagem:"assets/lee.jpg"
},

{
nome:"Itachi Uchiha",
vila:"Akatsuki",
rank:"S",
chakra:99,
nivel:100,
imagem:"assets/itachi.jpg"
},

{
nome:"Pain",
vila:"Akatsuki",
rank:"S",
chakra:100,
nivel:100,
imagem:"assets/pain.jpg"
},

{
nome:"Madara Uchiha",
vila:"Folha",
rank:"Lendário",
chakra:100,
nivel:100,
imagem:"assets/madara.jpg"
}
];

const container=document.getElementById("container");
const pesquisa=document.getElementById("search");
const filtro=document.getElementById("vila");

function criarCard(personagem){

return `

<div class="card fade">

<img src="${personagem.imagem}" alt="${personagem.nome}">

<div class="card-content">

<h2>${personagem.nome}</h2>

<p><strong>Vila:</strong> ${personagem.vila}</p>

<p><strong>Rank:</strong> ${personagem.rank}</p>

<div class="status">

<span>Chakra</span>

<div class="bar">
<div class="fill" style="width:${personagem.chakra}%"></div>
</div>

</div>

<div class="status">

<span>Nível</span>

<div class="bar">
<div class="fill" style="width:${personagem.nivel}%"></div>
</div>

</div>

</div>

</div>

`;

}

function mostrar(lista){

container.innerHTML="";

lista.forEach(personagem=>{

container.innerHTML+=criarCard(personagem);

});

}

mostrar(personagens);

pesquisa.addEventListener("keyup",()=>{

const texto=pesquisa.value.toLowerCase();

const vila=filtro.value;

const resultado=personagens.filter(p=>{

const nome=p.nome.toLowerCase().includes(texto);

const vilaOk=vila==="Todos" || p.vila===vila;

return nome && vilaOk;

});

mostrar(resultado);

});

filtro.addEventListener("change",()=>{

const texto=pesquisa.value.toLowerCase();

const vila=filtro.value;

const resultado=personagens.filter(p=>{

const nome=p.nome.toLowerCase().includes(texto);

const vilaOk=vila==="Todos" || p.vila===vila;

return nome && vilaOk;

});

mostrar(resultado);

});